apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
    - name: init-myservice
      image: busybox:1.36
      command: ["sh", "-c", "echo The app is starting!; sleep 10"]
  containers:
    - name: c1
      image: nginx:latest
