apiVersion: v1
kind: Pod
metadata:
  name: livepod
spec:
  containers:
    - name: myapp
      image: nginx
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
    - name: sidecar
      image: busybox
      command: ["/bin/sh", "-c", "echo Sidecar container running; sleep 3600"]
