apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testpodnp
spec:
  podSelector:
    matchLabels:
      app: xyz
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
