apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-rs
  namespace: demo
  labels:
    app: hello
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      tier: frontend
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
      annotations:
        demo/owner: "Himanshu Rathi"
        demo/purpose: "ReplicaSet demo"
    spec:
      containers:
        - name: web
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
