apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: demo
spec:
  completions: 7
  parallelism: 3
  backoffLimit: 2

  template:
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: busybox:1.36
          command: ["sh", "-c", "echo Job run at $(date); sleep 3; echo done"]
