apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
  namespace: demo
spec:
  schedule: "* * * * *" # every minute
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: tick
              image: busybox:1.36
              command: ["sh", "-c", "date; echo Hello from CronJob"]
