apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
  namespace: demo
spec:
  schedule: "*/2 * * * *" # every 2 minutes
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: tick
              image: busybox:1.36
              command: ["sh","-c","date; echo Hello from CronJob"]
