apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # lives beyond the life of the pod
  storageClassName: ""
  hostPath:
    path: /home/docker/demopv
    type: Directory
