apiVersion: v1
kind: Pod
metadata:
  name: hostpod
  labels:
    app: hostpod
spec:
  containers:
    - name: host1
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: host-vol
    - name: host2
      image: rockylinux:9
      command:
        [
          /bin/sh,
          -c,
          'while true; do X=$[$X+1]; echo "$X" > /usr/share/nginx/html/index.html; sleep 1; done',
        ]
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: host-vol
  volumes:
    - name: host-vol
      hostPath:
        path: /home/docker/hostvol
        type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: hostsvc
spec:
  type: NodePort
  selector:
    app: hostpod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
