apiVersion: v1
kind: Pod
metadata:
  name: pod-node1
  labels:
    app: pod-node1
spec:
  nodeSelector:
    env: dev
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
